### ISSUE TITLE
installed shared library looses (some) dependencies

### ISSUE THREAD

**Issue by pnorbert** [ornladios/ADIOS2#348] opened 2017-12-12 16:06 UTC
I built ADIOS2 with SST and ZFP. The shared library in the build directory shows the dependencies:

~/work/ADIOS2/build/bindings/fortran$ ldd ../../lib/libadios2.so
	linux-vdso.so.1 =>  (0x00007fff701f8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f063bbff000)
	libzmq.so.5 => /usr/lib/x86_64-linux-gnu/libzmq.so.5 (0x00007f063b999000)
	libsst.so => /home/adios/work/ADIOS2/build/lib/libsst.so (0x00007f063b78c000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f063b57c000)
	libzfp.so.0 => /opt/zfp/lib/libzfp.so.0 (0x00007f063b357000)
        ...
However, the installed library (after make install), looses track of SST and ZFP. SST is built with ADIOS2, ZFP is an external dependency:

adios@adiosVM:~/work/ADIOS2/build/bindings/fortran$ ldd /opt/adios2/lib/libadios2.so
	linux-vdso.so.1 =>  (0x00007ffd7cbb7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f35578ba000)
	libzmq.so.5 => /usr/lib/x86_64-linux-gnu/libzmq.so.5 (0x00007f3557654000)
	libsst.so => not found
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f3557444000)
	libzfp.so.0 => not found
	libhdf5.so.10 => /opt/hdf5-1.8.17-parallel/lib/libhdf5.so.10 (0x00007f3556f23000)
        ...

Moreover, adios2-config --libs does not include any dependencies:
$ /opt/adios2/bin/adios2-config --libs
-L/opt/adios2/lib -ladios2 -L/usr/lib/openmpi/lib -lpthread -lmpi

**Comment by williamfgc** [comment] 2017-12-12 18:04
Related to rpath issue #333

**Comment by chuckatkins** [comment] 2017-12-13 19:12
The adios2-config needs to be fixed.  However, the missing library references after install is by design.  RPATH information is stripped during install.

**Comment by chuckatkins** [comment] 2018-12-31 20:14
Fixed in #1081

**Closed by chuckatkins** 2018-12-31 20:14 UTC
Labels: bug
