### ISSUE TITLE
Cannot build Adios/2.8.3 on Cray XC40/50 HPC System

### ISSUE THREAD

**Issue by jshafner** [ornladios/ADIOS2#3473] opened 2023-02-07 15:14 UTC
Working with a helpdesk to install 2.8.3 on a Cray System (but building with intel environment variable). See below:

Here are the CMake install errors that I am trying to iron out. It seems that the "make" worked, but this "make install" is being tripped up in a way that 2.7.1 didn't face. So far, adding the recommended variables hasn't solved it though I haven't tried CMAKE_PREFIX_PATH yet. If you or your team have any ideas, I would be happy to try them. I can also send my build script as it is so far.

`CMake Error at CMakeLists.txt:9 (find_package):
By not providing "Findadios2.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "adios2", but
CMake did not find one.
 
Could not find a package configuration file provided by "adios2" with any
of the following names:
 
adios2Config.cmake
adios2-config.cmake
 
Add the installation prefix of "adios2" to CMAKE_PREFIX_PATH or set
"adios2_DIR" to a directory containing one of the above files. If "adios2"
provides a separate development package or SDK, be sure it has been
installed.`

**Comment by jshafner** [comment] 2023-02-07 20:11
Here is a copy of the mentioned build script.

[Adios283build.txt](https://github.com/ornladios/ADIOS2/files/10679017/Adios283build.txt)

**Comment by vicentebolea** [comment] 2023-08-24 00:04
If you do not need Makefile support for ADIOS2 and only use cmake you can speficy `-DADIOS2_INSTALL_GENERATE_CONFIG=OFF` at configure time to skip this error.

**Comment by vicentebolea** [comment] 2023-09-04 18:28
I believe that this has been resolved in #3760

**Comment by vicentebolea** [comment] 2024-07-19 22:15
Closing this since we cannot reproduce this anymore. Please re-open if you observe this again

**Closed by vicentebolea** 2024-07-19 22:15 UTC
Labels: area: build
