### ISSUE TITLE
MPI tests running with 1 process by default

### ISSUE THREAD

**Issue by williamfgc** [ornladios/ADIOS2#639] opened 2018-05-21 12:50 UTC
mpirun -n 4 is used for bindings (Fortran, Python) tests, but not for C++ or C, running on Ubuntu 16.04, gcc 5.4.0, cmake 3.11.1, openmpi 1.10.2

```$ ctest -V | grep "Test command"
1: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_int8_t_1x10"
2: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_int16_t_1x10"
3: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_int32_t_1x10"
4: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_int64_t_1x10"
5: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_uint8_t_1x10"
6: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_uint16_t_1x10"
7: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_uint32_t_1x10"
8: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_uint64_t_1x10"
9: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_int8_t_2x5"
10: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_int16_t_2x5"
11: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_int32_t_2x5"
12: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_int64_t_2x5"
13: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_uint8_t_2x5"
14: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_uint16_t_2x5"
15: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_uint32_t_2x5"
16: Test command: /home/wfg/workspace/build/bin/TestADIOSInterfaceWrite "--gtest_filter=ADIOSInterfaceWriteTest.DefineVar_uint64_t_2x5"
17: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineGlobalValue"
18: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineLocalValue"
19: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineGlobalArray"
20: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineGlobalArrayWithSelections"
21: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineGlobalArrayConstantDims"
22: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineGlobalArrayInvalidLocalValueDim"
23: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineLocalArray"
24: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineLocalArrayWithSelection"
25: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineLocalArrayConstantDims"
26: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineLocalArrayInvalidOffsets"
27: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineJoinedArrayFirstDim"
28: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineJoinedArraySecondDim"
29: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineJoinedArrayTooManyJoinedDims"
30: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineJoinedArrayInvalidStart"
31: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineString"
32: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineAndRemove"
33: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineVariable "--gtest_filter=ADIOSDefineVariableTest.DefineAndRemoveAll"
34: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineAttribute "--gtest_filter=ADIOSDefineAttributeTest.DefineAttributeNameException"
35: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineAttribute "--gtest_filter=ADIOSDefineAttributeTest.DefineAttributeTypeByValue"
36: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineAttribute "--gtest_filter=ADIOSDefineAttributeTest.DefineAttributeTypeByReference"
37: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineAttribute "--gtest_filter=ADIOSDefineAttributeTest.GetAttribute"
38: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineAttribute "--gtest_filter=ADIOSDefineAttributeTest.DefineAndRemove"
39: Test command: /home/wfg/workspace/build/bin/TestADIOSDefineAttribute "--gtest_filter=ADIOSDefineAttributeTest.DefineAndRemoveAll"
40: Test command: /home/wfg/workspace/build/bin/TestBPWriteAggregateRead "--gtest_filter=BPWriteAggregateReadTest.ADIOS2BPWriteAggregateRead1D8"
41: Test command: /home/wfg/workspace/build/bin/TestBPWriteAggregateRead "--gtest_filter=BPWriteAggregateReadTest.ADIOS2BPWriteAggregateRead2D2x4"
42: Test command: /home/wfg/workspace/build/bin/TestBPWriteAggregateRead "--gtest_filter=BPWriteAggregateReadTest.ADIOS2BPWriteAggregateRead2D4x2"
43: Test command: /home/wfg/workspace/build/bin/TestBPWriteAggregateRead "--gtest_filter=BPWriteAggregateReadTest.ADIOS2BPWriteAggregateSubStreamsException"
44: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadADIOS2 "--gtest_filter=BPWriteReadTestADIOS2.ADIOS2BPWriteRead1D8"
45: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadADIOS2 "--gtest_filter=BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D2x4"
46: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadADIOS2 "--gtest_filter=BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2"
48: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadADIOS2 "--gtest_filter=BPWriteReadTestADIOS2.OpenEngineTwice"
49: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAsStreamADIOS2 "--gtest_filter=BPWriteReadAsStreamTestADIOS2.ADIOS2BPWriteRead1D8"
50: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAsStreamADIOS2 "--gtest_filter=BPWriteReadAsStreamTestADIOS2.ADIOS2BPWriteRead2D2x4"
51: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAsStreamADIOS2 "--gtest_filter=BPWriteReadAsStreamTestADIOS2.ADIOS2BPWriteRead2D4x2"
52: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAsStreamADIOS2 "--gtest_filter=BPWriteReadAsStreamTestADIOS2.ADIOS2BPWriteRead1D8MissingPerformGets"
53: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAsStreamADIOS2 "--gtest_filter=BPWriteReadAsStreamTestADIOS2.ADIOS2BPWriteRead2D2x4MissingPerformGets"
54: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAsStreamADIOS2 "--gtest_filter=BPWriteReadAsStreamTestADIOS2.ADIOS2BPWriteRead2D4x2MissingPerformGets"
55: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAsStreamADIOS2_Threads "--gtest_filter=BPWriteReadAsStreamTestADIOS2_Threads.ADIOS2BPWriteRead1D8"
56: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAsStreamADIOS2_Threads "--gtest_filter=BPWriteReadAsStreamTestADIOS2_Threads.ADIOS2BPWriteRead2D2x4"
57: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAsStreamADIOS2_Threads "--gtest_filter=BPWriteReadAsStreamTestADIOS2_Threads.ADIOS2BPWriteRead2D4x2"
58: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAttributesADIOS2 "--gtest_filter=BPWriteReadAttributeTestADIOS2.ADIOS2BPWriteReadSingleTypes"
59: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadAttributesADIOS2 "--gtest_filter=BPWriteReadAttributeTestADIOS2.ADIOS2BPWriteReadArrayTypes"
60: Test command: /home/wfg/workspace/build/bin/TestStreamWriteReadHighLevelAPI "--gtest_filter=StreamwriteReadHighLevelAPI.ADIOS2BPwriteRead1D8"
61: Test command: /home/wfg/workspace/build/bin/TestStreamWriteReadHighLevelAPI "--gtest_filter=StreamwriteReadHighLevelAPI.ADIOS2BPwriteRead2D2x4"
62: Test command: /home/wfg/workspace/build/bin/TestStreamWriteReadHighLevelAPI "--gtest_filter=StreamwriteReadHighLevelAPI.ADIOS2BPwriteRead2D4x2"
63: Test command: /home/wfg/workspace/build/bin/TestBPWriteFlushRead "--gtest_filter=BPWriteFlushRead.ADIOS2BPWrite1D2D"
64: Test command: /home/wfg/workspace/build/bin/TestBPWriteFlushRead "--gtest_filter=BPWriteFlushRead.ADIOS2BPWrite1D2Dstdio"
65: Test command: /home/wfg/workspace/build/bin/TestBPWriteFlushRead "--gtest_filter=BPWriteFlushRead.ADIOS2BPWrite1D2Dfstream"
66: Test command: /home/wfg/workspace/build/bin/TestInSituMPIFunctionAssignPeers "--gtest_filter=InSituMPIFunctionAssignPeersTest.3x2"
67: Test command: /home/wfg/workspace/build/bin/TestInSituMPIFunctionAssignPeers "--gtest_filter=InSituMPIFunctionAssignPeersTest.5x2"
68: Test command: /home/wfg/workspace/build/bin/TestInSituMPIFunctionAssignPeers "--gtest_filter=InSituMPIFunctionAssignPeersTest.8x3"
69: Test command: /home/wfg/workspace/build/bin/TestInSituMPIFunctionAssignPeers "--gtest_filter=InSituMPIFunctionAssignPeersTest.3x3"
70: Test command: /home/wfg/workspace/build/bin/TestInSituMPIFunctionAssignPeers "--gtest_filter=InSituMPIFunctionAssignPeersTest.2x3"
71: Test command: /home/wfg/workspace/build/bin/TestInSituMPIFunctionAssignPeers "--gtest_filter=InSituMPIFunctionAssignPeersTest.3x8"
72: Test command: /home/wfg/workspace/build/bin/TestInSituMPIFunctionAssignPeers "--gtest_filter=InSituMPIFunctionAssignPeersTest.3x13"
73: Test command: /home/wfg/workspace/build/bin/TestStagingMPMD "--gtest_filter=*/TestStagingMPMD.SingleStep/*" "InSituMPI"
74: Test command: /home/wfg/workspace/build/bin/TestStagingMPMD "--gtest_filter=*/TestStagingMPMD.MultipleSteps/*" "InSituMPI"
75: Test command: /home/wfg/workspace/build/bin/TestStagingMPMD "--gtest_filter=*/TestStagingMPMD.SlowWriter/*" "InSituMPI"
76: Test command: /home/wfg/workspace/build/bin/TestStagingMPMD "--gtest_filter=*/TestStagingMPMD.SlowReader/*" "InSituMPI"
77: Test command: /usr/bin/mpiexec "-n" "4" "/usr/bin/python3" "/home/wfg/workspace/ADIOS2/testing/adios2/bindings/python/TestBPWriteTypes.py"
78: Test command: /usr/bin/mpiexec "-n" "4" "/usr/bin/python3" "/home/wfg/workspace/ADIOS2/testing/adios2/bindings/python/TestBPWriteTypesHighLevelAPI.py"
79: Test command: /usr/bin/mpiexec "-n" "4" "/home/wfg/workspace/build/bin/TestBPWriteAttributes_f"
80: Test command: /usr/bin/mpiexec "-n" "4" "/home/wfg/workspace/build/bin/TestBPWriteTypesByName_f"
81: Test command: /usr/bin/mpiexec "-n" "4" "/home/wfg/workspace/build/bin/TestBPWriteStep_f"
82: Test command: /usr/bin/mpiexec "-n" "4" "/home/wfg/workspace/build/bin/TestBPWriteLocal_f"
83: Test command: /usr/bin/mpiexec "-n" "4" "/home/wfg/workspace/build/bin/TestBPWriteReadTypes_f"
84: Test command: /usr/bin/mpiexec "-n" "4" "/home/wfg/workspace/build/bin/TestBPWriteReadTypesHighLevelAPI_f"
85: Test command: /usr/bin/mpiexec "-n" "4" "/home/wfg/workspace/build/bin/TestRemove_f"
86: Test command: /home/wfg/workspace/build/bin/TestBPWriteTypes_c "--gtest_filter=BPWriteTypes.ADIOS2BPWriteTypes"
87: Test command: /home/wfg/workspace/build/bin/TestBPWriteTypesHighLevel_c "--gtest_filter=BPWriteTypesHighLevel.ADIOS2BPWriteTypes"
88: Test command: /home/wfg/workspace/build/bin/TestBPWriteReadADIOS2_cxx98 "--gtest_filter=BPWriteReadTestADIOS2_cxx98.ADIOS2BPWriteRead1D8"
89: Test command: /home/wfg/workspace/build/bin/TestXMLConfig "--gtest_filter=XMLConfigTest.TwoIOs"
90: Test command: /home/wfg/workspace/build/bin/TestXMLConfig "--gtest_filter=XMLConfigTest.TwoEnginesException"
91: Test command: /home/wfg/workspace/build/bin/TestManyVars "--gtest_filter=*/TestManyVars.DontRedefineVars/*"
```

**Comment by chuckatkins** [comment] 2018-05-25 13:47
This was caused by a mismatch in our local copy of GoogleTest.cmake and upstream.  This was fixed in #633

**Closed by chuckatkins** 2018-05-25 13:47 UTC
Labels: bug
