### ISSUE TITLE
summit anaconda build error

### ISSUE THREAD

**Issue by zeneofa** [ornladios/ADIOS2#1524] opened 2019-06-19 21:14 UTC
Hi, 

I am having problems trying to build adios2 on summit, using the anaconda environment. I seems that the adios2.cpython-36m-powerpc64le-linux-gnu.so file is not created all. I am building from the github master branch

```
╰─[:)] % git rev-parse HEAD
cbaf8ca92b4550cad603522e6570f3cbf95acdba
```

The modules that I have loaded:

```
Currently Loaded Modules:
  1) hsi/5.0.2.p5   3) lsf-tools/2.0           5) DefApps         7) python/3.6.6-anaconda3-5.3.0   9) cmake/3.14.2                    11) magma/2.3.0
  2) xalt/1.1.3     4) darshan-runtime/3.1.7   6) cuda/10.1.105   8) gcc/6.4.0                     10) spectrum-mpi/10.3.0.0-20190419
```

I use the following command to build

```
mkdir adios2-build
cd adios2-build
cmake -DCMAKE_C_COMPILER=${OMPI_CC} -DCMAKE_CXX_COMPILER=${OMPI_CXX} -DCMAKE_INSTALL_PREFIX=~/software/adios2 -DADIOS2_USE_Fortran=OFF -DADIOS2_USE_ZeroMQ=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DADIOS2_USE_SST=OFF .. 2>&1 | tee cmake.configure.adios2.log 
```

After this I run
```
make -j 1 2>&1 | tee  make.adios2.log 
```

which then errors with:
```
[ 38%] Building CXX object bindings/Python/CMakeFiles/adios2py.dir/py11glue.cpp.o
[ 39%] Linking CXX shared module ../../lib64/python3.6/site-packages/adios2.cpython-36m-powerpc64le-linux-gnu.so
lto1: internal compiler error: invalid line in the resolution file
0x101d225b lto_resolution_read
	/sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:1912
0x101d225b lto_file_read
	/sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:2092
0x101d225b read_cgraph_and_symbols
	/sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:2806
0x101d225b lto_main()
	/sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:3310
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: /sw/summit/gcc/6.4.0/bin/g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
/usr/bin/sha1sum: ../../lib64/python3.6/site-packages/adios2.cpython-36m-powerpc64le-linux-gnu.so: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [lib64/python3.6/site-packages/adios2.cpython-36m-powerpc64le-linux-gnu.so] Error 1
make[1]: *** [bindings/Python/CMakeFiles/adios2py.dir/all] Error 2
make: *** [all] Error 2
```

I have loaded the output logs on gist here: https://gist.github.com/zeneofa/9c6d8ccb102a8c21f45032dfce29846a

This seems to be anaconda specific, as when I use the standard python module I do not get the lto error. 

```
module unload python/3.6.6-anaconda3-5.3.0
module load python/3.7.0
```
This is independent of python version, using the anaconda 3.7 version also fails. 

Any help would be much appreciated. Thanks in advance.

P

**Comment by williamfgc** [comment] 2019-06-20 13:01
@zeneofa anaconda prefers their own gcc/g++ compilers: https://github.com/ContinuumIO/anaconda-issues/issues/6619  it's an anaconda issue. Not sure how Summit admins are handling this issue of mixing the system gcc with anaconda packages. Hope it helps.

**Comment by zeneofa** [comment] 2019-06-21 16:00
Thanks for the pointer. I was thinking of going down that route, but remember the nightmare associated with multiple different gcc's and lots of broken environments, so I was hesitant at first. Anaconda has since changed the way it handles these anaconda compilers, which I am so happy about. 

I have managed to get things compiled using the anaconda gxx and gcc compilers in a test conda environment. I am hoping to turn this into a recipe to be able to install this into our groups main conda environment. At the moment running into cmake FindMPI issues. I will also need to test portability, to see if this works without polluting the main environment with the anaconda compilers.

**Comment by williamfgc** [comment] 2019-06-24 18:00
@zeneofa thanks for following up and sharing your plans. My experience with anaconda is that it's great for pre-compiled packages from anaconda cloud, but I ran into similar difficulties when building from source and mixing compilers from system environments. Still, we are having a release at the of the month, we are going to put a release into anaconda cloud, potentially [conda-forge](https://github.com/conda-forge/staged-recipes/pull/8526) but not without issues.

**Comment by suchyta1** [comment] 2019-08-08 13:52
I'm not sure this is specific to Conda. I'm building using Spack and getting this, regardless of which version of gcc I choose. It's possible Spack cleans the environment such that it's missing something needed. So I also tried building without Spack and see the same thing. I wouldn't call it completely convincing though, b/c I copied the CMake line for how Spack ran CMake. I have my shell environment in that case, but it is verbatim the same CMake call Spack ran, just actually in the shell.

**Comment by suchyta1** [comment] 2019-08-08 13:59
Actually mine is a little different. I'm seeing it after bpls has been build (which might be the last thing?). And it doesn't even look like it's building anything when the error happens. It looks like it might be when something is exiting.

```
[100%] Linking CXX executable ../../bin/bpls
cd /tmp/esuchyta/spack-stage/spack-stage-e_eytfla/ADIOS2/spack-build/source/utils && /gpfs/alpine/csc143/world-shared/esuchyta/spack/install/linux-rhel7-ppc64le/gcc-6.4.0/cmake-3.13.1-lx5es2zy5tujxg74r5z33syeehcwcpug/bin/cmake -E cmake_link_script CMakeFiles/bpls.dir/link.txt --verbose=1
/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.1-20190611-cyaenjgora6now2nusxzkfli4mzjnudx/bin/mpicxx  -O3 -DNDEBUG  -pthread CMakeFiles/bpls.dir/bpls/bpls.cpp.o CMakeFiles/bpls.dir/__/__/thirdparty/pugixml/pugixml/src/pugixml.cpp.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/EncodingC.c.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/Directory.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/DynamicLoader.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/EncodingCXX.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/RegularExpression.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/SystemTools.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/CommandLineArguments.cxx.o ../../thirdparty/KWSys/adios2sys/CMakeFiles/adios2sys_objects.dir/FStream.cxx.o  -o ../../bin/bpls -Wl,-rpath,/tmp/esuchyta/spack-stage/spack-stage-e_eytfla/ADIOS2/spack-build/lib64: ../../lib64/libadios2.so.2.4.0 -lpthread /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.1-20190611-cyaenjgora6now2nusxzkfli4mzjnudx/lib/libmpiprofilesupport.so /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.0.1-20190611-cyaenjgora6now2nusxzkfli4mzjnudx/lib/libmpi_ibm.so -ldl -Wl,-rpath-link,/tmp/esuchyta/spack-stage/spack-stage-e_eytfla/ADIOS2/spack-build/lib64
make[2]: Leaving directory `/tmp/esuchyta/spack-stage/spack-stage-e_eytfla/ADIOS2/spack-build'
[100%] Built target bpls
lto1: internal compiler error: invalid resolution in the resolution file
0x101d0e93 lto_resolution_read
    /sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:1923
0x101d0e93 lto_file_read
    /sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:2092
0x101d0e93 read_cgraph_and_symbols
    /sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:2806
0x101d0e93 lto_main()
    /sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:3310
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: /autofs/nccs-svm1_sw/summit/gcc/6.4.0/bin/g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
/usr/bin/sha1sum: ../../lib64/python3.7/site-packages/adios2.cpython-37m-powerpc64le-linux-gnu.so: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [lib64/python3.7/site-packages/adios2.cpython-37m-powerpc64le-linux-gnu.so] Error 1
make[2]: Leaving directory `/tmp/esuchyta/spack-stage/spack-stage-e_eytfla/ADIOS2/spack-build'
make[1]: *** [bindings/Python/CMakeFiles/adios2py.dir/all] Error 2
make[1]: Leaving directory `/tmp/esuchyta/spack-stage/spack-stage-e_eytfla/ADIOS2/spack-build'
make: *** [all] Error 2
```

**Comment by williamfgc** [comment] 2019-08-08 14:18
Hi @suchyta1  you're correct, it's not conda, but environment specific related. I don't know how spack or conda resolves conflicts with the python system libraries and environment. adios2 compiles without conda and spack on Summit as reported above. conda and spack add another degree of freedom on top of Summit modules for your environment. 

Seems `../../lib64/python3.7/site-packages/adios2.cpython-37m-powerpc64le-linux-gnu.so: No such file or directory` is not even built.  Can you share the output or the cmake config step? Thanks.

**Comment by suchyta1** [comment] 2019-08-08 14:33
(Spack wipes the environment before starting -- at least in principle.) I attached my whole output log. 

[spack-build.txt](https://github.com/ornladios/ADIOS2/files/3482231/spack-build.txt)

**Comment by suchyta1** [comment] 2019-08-08 14:39
Oh, I think it's my python library step that's failing. I'm building in parallel, so bpls probably finished while the python part is going. Mine is probably b/c I'm using my own version of Python built with Spack, instead of a system one, but IDK.

**Comment by suchyta1** [comment] 2019-08-08 17:01
This isn't an ideal solution, but it works if you do a debug build. I think what's going wrong is using `-flto`, (which does link time optimization, i.e. `lto`), but somehow it's only the step trying to link the python `.so` which has an issue, which is curious. So making sure `-fno-lto` would probably work, too. I  don't know how much that would affect performance. And FWIW, I used to build the same way, and the `-flto` was fine. I'd be surprised if the answer isn't something buried really deep in the environment that changed after Summit upgrades happened.

@williamfgc (or other ADIOS†

**Comment by williamfgc** [comment] 2019-08-09 01:46
Hi @suchyta1 , thanks for digging deeper and narrowing this down. I think we should file a ticker with Summit. In all honesty, I am not aware how much they support conda/spack environments. Still, if it worked for you in the past they probably would be interested in the issue with `-flto`. To answer your question, any build type other than Release (-O3 by default) will affect performance.

**Comment by ax3l** [comment] 2020-07-23 01:58
Google brought me here. When compiling our app (WarpX) on Summit with the default GCC 6.4.0 module I also get an ICE when using LTO. This could be a GCC bug...
Maybe it's worth checking if newer GCC fix that on PPC64le or if one should report his upstream.
```
lto1: internal compiler error: invalid resolution in the resolution file
0x101d0e93 lto_resolution_read
	/sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:1923
0x101d0e93 lto_file_read
	/sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:2092
0x101d0e93 read_cgraph_and_symbols
	/sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:2806
0x101d0e93 lto_main()
	/sw/summit/gcc/6.4.0/src/gcc-6.4.0/gcc/lto/lto.c:3310
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: /sw/summit/gcc/6.4.0/bin/g++ returned 1 exit status
compilation terminated.
```

**Comment by ax3l** [comment] 2020-07-23 02:31
`gcc/7.4.0` and `gcc/9.1.0` (aka `9.1.0-alpha+20190716`) have the same problem. Probably worth reporting upstream with GCC with a smaller reproducer.
```
lto1: internal compiler error: invalid line in the resolution file
0x101915bb lto_resolution_read
	/tmp/belhorn/gcc-build-9.1.0-alpha+20190716/gcc-9.1.0/gcc/lto/lto.c:1957
0x101915bb lto_file_read
	/tmp/belhorn/gcc-build-9.1.0-alpha+20190716/gcc-9.1.0/gcc/lto/lto.c:2142
0x10191c57 read_cgraph_and_symbols
	/tmp/belhorn/gcc-build-9.1.0-alpha+20190716/gcc-9.1.0/gcc/lto/lto.c:2849
0x10191c57 lto_main()
	/tmp/belhorn/gcc-build-9.1.0-alpha+20190716/gcc-9.1.0/gcc/lto/lto.c:3387
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
lto-wrapper: fatal error: /sw/summit/gcc/9.1.0-alpha+20190716/bin/g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
```

**Comment by ax3l** [comment] 2020-07-27 17:36
Filed as https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96343. If anyone finds a small reproducer then please share :)

**Comment by eisenhauer** [comment] 2023-12-12 19:28
@ax3l, Closing this as very old and since it was filed with gcc and rejected there I think it wasn't an ADIOS problem.

**Closed by eisenhauer** 2023-12-12 19:28 UTC
Labels: not-a-bug
