### ISSUE TITLE
Feature request: Julia bindings

### ISSUE THREAD

**Issue by rkube** [ornladios/ADIOS2#2802] opened 2021-07-28 10:11 UTC
Hi,
any chance that bindings for [julia](https://julialang.org/) will be implemented in the future?

**Comment by eschnett** [comment] 2021-07-30 13:33
I implemented Julia bindings in a Julia package https://github.com/eschnett/ADIOS2.jl, but calling the C API.

**Comment by williamfgc** [comment] 2023-01-26 19:20
@rkube @eschnett we can safely close this issue. Thanks for the great effort 👍

**Closed by williamfgc** 2023-01-26 19:20 UTC

**Comment by williamfgc** [comment] 2023-01-26 19:44
duplicate of #426
