### ISSUE TITLE
Error on python helloBPWriter example

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#1233] opened 2019-02-26 15:10 UTC
Just tried to run helloBPWriter.py but got the following error:
```
[jychoi-mbp:78772] *** Process received signal ***
[jychoi-mbp:78772] Signal: Abort trap: 6 (6)
[jychoi-mbp:78772] Signal code:  (0)
[jychoi-mbp:78772] [ 0] 0   libsystem_platform.dylib            0x00007fff612d1f5a _sigtramp + 26
[jychoi-mbp:78772] [ 1] 0   ???                                 0x00007ffe00020008 0x0 + 140728898551816
[jychoi-mbp:78772] [ 2] 0   libsystem_c.dylib                   0x00007fff6106f1ae abort + 127
[jychoi-mbp:78772] [ 3] 0   libc++abi.dylib                     0x00007fff5ef69f8f __cxa_bad_cast + 0
[jychoi-mbp:78772] [ 4] 0   libc++abi.dylib                     0x00007fff5ef6a113 _ZL25default_terminate_handlerv + 241
[jychoi-mbp:78772] [ 5] 0   libobjc.A.dylib                     0x00007fff603abeab _ZL15_objc_terminatev + 105
[jychoi-mbp:78772] [ 6] 0   libc++abi.dylib                     0x00007fff5ef857c9 _ZSt11__terminatePFvvE + 8
[jychoi-mbp:78772] [ 7] 0   libc++abi.dylib                     0x00007fff5ef8526f _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
[jychoi-mbp:78772] [ 8] 0   adios2.cpython-37m-darwin.so        0x0000000114cedc07 _ZN8pybind114reprENS_6handleE + 119
[jychoi-mbp:78772] [ 9] 0   adios2.cpython-37m-darwin.so        0x0000000114ce846c _ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_ + 18140
[jychoi-mbp:78772] [10] 0   python                              0x00000001026a9958 _PyMethodDef_RawFastCallKeywords + 392
[jychoi-mbp:78772] [11] 0   python                              0x00000001026a9420 _PyObject_FastCallKeywords + 592
[jychoi-mbp:78772] [12] 0   python                              0x00000001027e9be4 call_function + 404
[jychoi-mbp:78772] [13] 0   python                              0x00000001027e7684 _PyEval_EvalFrameDefault + 45284
[jychoi-mbp:78772] [14] 0   python                              0x00000001027db2d2 _PyEval_EvalCodeWithName + 418
[jychoi-mbp:78772] [15] 0   python                              0x00000001027d60bb builtin_exec + 347
[jychoi-mbp:78772] [16] 0   python                              0x00000001026a98b6 _PyMethodDef_RawFastCallKeywords + 230
[jychoi-mbp:78772] [17] 0   python                              0x00000001027e9b47 call_function + 247
[jychoi-mbp:78772] [18] 0   python                              0x00000001027e76bf _PyEval_EvalFrameDefault + 45343
[jychoi-mbp:78772] [19] 0   python                              0x00000001026c29f4 gen_send_ex + 180
[jychoi-mbp:78772] [20] 0   python                              0x00000001027e2837 _PyEval_EvalFrameDefault + 25239
[jychoi-mbp:78772] [21] 0   python                              0x00000001026c29f4 gen_send_ex + 180
[jychoi-mbp:78772] [22] 0   python                              0x00000001027e2837 _PyEval_EvalFrameDefault + 25239
[jychoi-mbp:78772] [23] 0   python                              0x00000001026c29f4 gen_send_ex + 180
[jychoi-mbp:78772] [24] 0   python                              0x00000001026a9853 _PyMethodDef_RawFastCallKeywords + 131
[jychoi-mbp:78772] [25] 0   python                              0x00000001026b68c4 _PyMethodDescr_FastCallKeywords + 84
[jychoi-mbp:78772] [26] 0   python                              0x00000001027e9bd7 call_function + 391
[jychoi-mbp:78772] [27] 0   python                              0x00000001027e75ee _PyEval_EvalFrameDefault + 45134
[jychoi-mbp:78772] [28] 0   python                              0x00000001026a9078 function_code_fastcall + 120
[jychoi-mbp:78772] [29] 0   python                              0x00000001027e9afe call_function + 174
[jychoi-mbp:78772] *** End of erro
```

I think the error happens in the following line:
```
# ADIOS Variable name, shape, start, offset, constant dims
ioArray = bpIO.DefineVariable(
    "bpArray", [size * Nx], [rank * Nx], [Nx], adios2.ConstantDims, myArray)
```

**Comment by germasch** [comment] 2019-02-26 16:03
This is at least partially caused by what looks like an out-of-date example. After these changes, it will work (or at least, not crash):
```diff
diff --git a/examples/hello/bpWriter/helloBPWriter.py b/examples/hello/bpWriter/helloBPWriter.py
index 20b7bf093..306d86dc9 100644
--- a/examples/hello/bpWriter/helloBPWriter.py
+++ b/examples/hello/bpWriter/helloBPWriter.py
@@ -23,7 +23,7 @@ adios = adios2.ADIOS(comm, adios2.DebugON)

 # ADIOS IO
 bpIO = adios.DeclareIO("BPFile_N2N")
-bpIO.SetEngine('BPFileWriter')
+bpIO.SetEngine('bp3')
 # bpIO.SetParameters( {"Threads" : "2", "ProfileUnits" : "Microseconds",
 # "InitialBufferSize" : "17Kb"} )
 bpIOParams = {}
@@ -36,7 +36,7 @@ fileID = bpIO.AddTransport('File', {'Library': 'fstream'})

 # ADIOS Variable name, shape, start, offset, constant dims
 ioArray = bpIO.DefineVariable(
-    "bpArray", [size * Nx], [rank * Nx], [Nx], adios2.ConstantDims, myArray)
+    "bpArray", myArray, [size * Nx], [rank * Nx], [Nx], adios2.ConstantDims)

 # ADIOS Engine
 bpFileWriter = bpIO.Open("npArray.bp", adios2.Mode.Write)
```

The second change is the main issue, the order of arguments was wrong. The first change just makes it use a supported engine.

While the example is easily fixed, there's a bigger underlying issue here in that it shouldn't crash like that when passing wrong arguments.

**Comment by williamfgc** [comment] 2019-02-26 16:10
@jychoi-hpc please look under the testing area for functional python tests/examples. Thanks for reporting this, no one had the time to look or maintain python examples as they are not tested on CI.

**Comment by jychoi-hpc** [comment] 2019-02-26 16:43
@germasch @williamfgc Thank you for the quick reply. It works now.

If there is a way to check parameters without making a crash, it would be great.

**Comment by williamfgc** [comment] 2019-02-26 17:02
@jychoi-hpc good point, unfortunately, we are highly dependent on PyBind11 for this and how it passes numpy arrays (which seems to be the issue at a first glance,  but I didn't dig deeper). For the most part we'll throw an exception if user input is not correct, but this is triggered at the PyBind11 layer. To be fair, #1234 reports that a functions signature is not found at this is triggered by the Python layer (adios2.so) due to a missing (not wrong) argument.

**Comment by germasch** [comment] 2019-03-03 18:24
I've traced this crash deep into pybind11, to the point where I sort of understand it. But anyway, it's not an ADIOS2 issue, for more info you can see here: https://github.com/pybind/pybind11/issues/1716

There's a patch there that works around the problem, but I'm not positive it's the right fix. In any case, hopefully this will get fixed upstream.

**Comment by germasch** [comment] 2019-03-05 20:50
@jychoi-hpc @williamfgc, the fix for the main issue here has been merged, so you may want to close it -- unless you want to keep it as reminder for the python crash caused by the overload resolution in pybind11.

**Comment by jychoi-hpc** [comment] 2019-03-06 15:50
Thank you for the fix. I will close this issue for now.

**Closed** 2019-03-06 15:50 UTC
