### ISSUE TITLE
SST RDMA tests are not using RDMA DP

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#1531] opened 2019-06-21 11:30 UTC
I'm not 100% sure, but I think the SST RDMA tests are not using the RDMA DP. Currently, if RDMA-capable interfaces are unavailable, the RDMA DP doesn’t try to use the generic `sockets` fabric provider and gives up (unless a specific interface is forced via `FABRIC_IFACE` or `DataInterface`). Therefore, SST always falls back to EVPath DP on a system without RDMA. I am not sure about the CI servers, but at least on my laptop, the RDMA tests (e.g. `HeatTransfer.SST.BP.RDMA.MxN `) are actually using EVPath.

**Comment by eisenhauer** [comment] 2019-06-21 15:58
That there is a clean fallback to the EVPath Data Plane is largely by design.  If there is no supported RDMA data plane available, the EVPath version is likely to be more performant than the sockets fabric provider, so we try not to fall back to that.  Unfortunately, it's very hard to determine at ADIOS2 compile time whether or not anything libfabric provides will actually be useful.  So it's mostly run-time determinations that we want to have reasonable fallbacks. 

So, I'm going to close this issue.  However, if there's some circumstance where you really want to use the sockets libfabric provider and want us to have some mechanism for forcing it, please re-open or resubmit.

**Closed by eisenhauer** 2019-06-21 15:58 UTC

**Comment by keichi** [comment] 2019-06-21 16:11
It's okay to fall back to EVPath if no RDMA fabric is available. What I'm concerned about is that we are not testing the RDMA DP in the CI at all.
