### ISSUE TITLE
Append mode error

### ISSUE THREAD

**Issue by jychoi-hpc** [ornladios/ADIOS2#2042] opened 2020-03-16 17:34 UTC
**Describe the bug**
I am working on Pixie3D to write restart files with appending mode without any success. I wrote a test case to reproduce the error. 

In the test code, I am trying to write a file with appending mode but getting an error. 
When writing with `adios2_mode_write`, it works. But, a file with `adios2_mode_append` is corrupted and cannot do `bpls` (no error during the runtime though).

**To Reproduce**
Here is my test code (writer.F90)
```
program writer
    use mpi
    use adios2

    implicit none

    integer(kind=8), dimension(1) :: shape_dims, start_dims, count_dims
    real, dimension(:), allocatable :: myArray
    integer :: inx, irank, isize, ierr, i, var1_type
    type(adios2_adios) :: adios
    type(adios2_io) :: io
    type(adios2_variable) :: var, var1
    type(adios2_attribute) :: attr
    type(adios2_engine) :: engine
    character(len=:), allocatable :: var1_name
    integer :: comm
    integer :: istatus

    real*8 :: totalpe;
    CHARACTER(len=32) :: arg
    integer :: mode
    logical :: do_read = .false.
    logical :: do_append = .false.

    do i = 1, iargc()
        call getarg(i, arg)
        if (trim(arg)=='-read') do_read = .true.
        if (trim(arg)=='-append') do_append = .true.
    end do

    ! Launch MPI
    comm = MPI_COMM_WORLD
    call MPI_Init(ierr)
    call MPI_Comm_rank(comm, irank, ierr)
    call MPI_Comm_size(comm, isize, ierr)

    ! Application variables
    inx = 10
    allocate( myArray(inx) )

    do i=1,inx
        myArray(i) = i-1
    end do

    ! Variable dimensions
    shape_dims(1) = isize * inx
    start_dims(1) = irank * inx
    count_dims(1) = inx

    if (do_append) then
        print *, 'Mode: append'
        mode = adios2_mode_append
    else
        print *, 'Mode: write'
        mode = adios2_mode_write
    endif

    ! Create adios handler passing the communicator, debug mode and error flag
    call adios2_init(adios, comm, adios2_debug_mode_on, ierr)

    ! Declare an IO process configuration inside adios
    call adios2_declare_io(io, adios, "group1", ierr)

    ! Defines a variable to be written in bp format
    ! call adios2_define_variable(var, io, 'totalpe', adios2_type_dp, ierr)
    call adios2_define_variable(var1, io, "totalpe", adios2_type_dp, 1, &
                                (/ 1_8 /), (/ 0_8 /), (/ 1_8 /), &
                                adios2_constant_dims, ierr)
    call adios2_define_variable(var1, io, "arr1", adios2_type_real, 1, &
                                shape_dims, start_dims, count_dims, &
                                adios2_constant_dims, ierr)
    call adios2_define_attribute(attr, io, "attr", "this is attr", ierr)

    ! Open myVector_f.bp in write mode, this launches an engine
    call adios2_open(engine, io, "out.bp", mode, comm, ierr)
    print *, 'adios2_open:ierr', ierr
    do i=1,4
        call adios2_begin_step(engine, adios2_step_mode_append, ierr)
        print *, 'adios2_begin_step:ierr', ierr

        ! Put myArray contents to bp buffer, based on var1 metadata
        call adios2_put(engine, 'totalpe', 777D0, ierr)
        call adios2_put(engine, var1, myArray, adios2_mode_sync, ierr)

        ! Closes engine and deallocates it, becomes unreachable
        call adios2_end_step(engine, ierr)
        print *, 'adios2_end_step:ierr', ierr
    enddo
    call adios2_close(engine, ierr)
    print *, 'adios2_close:ierr', ierr

    ! Deallocates adios and calls its destructor
    call adios2_finalize(adios, ierr)

    if( allocated(myArray) ) deallocate(myArray)
    if( allocated(var1_name) ) deallocate(var1_name)

    call MPI_Finalize(ierr)

end program writer
```

Makefile
```
FC=mpif90

ADIOS2_DIR=/opt/adios2
ADIOS2_INC=$(shell $(ADIOS2_DIR)/bin/adios2-config --fortran-flags)
ADIOS2_LIB=$(shell $(ADIOS2_DIR)/bin/adios2-config --fortran-libs)

BINS=writer
all: $(BINS)

writer: writer.F90
	$(FC) -g -ffree-line-length-0 $(ADIOS2_INC) -o $@ $? $(ADIOS2_LIB)

clean:
	rm -rf $(BINS) *.o *.dSYM
```

I am running in the following step. First, I create `out.bp` with `adios2_mode_write` mode
```bash
$ ./writer
$ bpls -lva out.bp
File info:
  of variables:  2
  of attributes: 1
  statistics:    Min / Max 

  float    arr1     4*{10} = 0 / 9
  string   attr     attr   = "this is attr"
  double   totalpe  4*{1} = 777 / 777
```
it works fine

Then, I am trying to do with `adios2_mode_append`:
```bash
$ ./writer -append
$ bpls -lva out.bp
$ bpls -lva out.bp/
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 0:
  #000: H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1700 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
```

It should be `BP4` file, not HDF5. It looks like the file corrupted.

Any help and advice will be appreciated.

Thanks.

**Comment by pnorbert** [comment] 2020-03-16 17:42
I can reproduce it but don't know the problem yet.

**Comment by lwan86** [comment] 2020-03-16 19:17
My guess is the append mode is not correctly handled by the fortran binding. I never tested with fortran code.

**Comment by pnorbert** [comment] 2020-03-16 19:20
It's the attribute that causes the bug to appear. The attribute is accepted to be appended and so two copies will exist in the BP file. Then the reader fails during open. The existing append test in the ADIOS2 source only tests variables not attributes. 

The error on the reader side in C++ would look like this:
`C++ exception with description "ERROR: attribute attr exists in IO object group1, in call to DefineAttribute`

bpls also can show the reason with more verbosity option:

```
$ /opt/adios2/bin/bpls  -la out.bp/ -vvv
Settings :
  masks  : 0 
  file   : out.bp/
  output : stdout
      -l : show scalar values and min/max/avg of arrays
      -a : list attributes too

ADIOS Open: read header info from out.bp
Try BPFile engine to open the file...
Failed to open with BPFile engine: ERROR: attribute attr exists in IO object bpls, in call to DefineAttribute

Error: Could not open this file with any ADIOS2 file reading engines
```

**Comment by lwan86** [comment] 2020-03-16 19:23
I see. @pnorbert Do you want me to fix this bug or you can do it?

**Comment by pnorbert** [comment] 2020-03-16 19:30
Where should this be fixed? At open for append? I think the attributes that are present in the file should be flagged as already written to avoid writing them the second time? 

Or should we allow for updating an existing attribute during open for read when processing attributes?

Eventually we will want mutual attributes so the second option sounds logical but those may be different objects later while we want to keep the current attribute concept as constant labels.

**Comment by pnorbert** [comment] 2020-03-16 19:42
First of all, I see that the append mode does not read in the attributes. 
If I add this to `ADIOS2/testing/adios2/engine/bp/TestBPWriteAppendReadADIOS2.cpp`
```
line 90:
        int16_t x  = 42;
        io.DefineAttribute<int16_t>("att16", x);
line 211:
        adios2::Engine bpAppender = io.Open(fname, adios2::Mode::Append);
        auto attrs = io.AvailableAttributes();
        EXPECT_EQ(attrs.size(), 1);
```
The tests `Engine.BP.BPWriteAppendReadTestADIOS2.ADIOS2BPWriteAppendRead2D2x4.BP4` will fail because the size of attrs will be zero.

**Comment by lwan86** [comment] 2020-03-16 19:51
No. Current implementation of append mode does not handle the attributes when open.

**Comment by lwan86** [comment] 2020-03-16 19:55
I think handling it when open for read makes more sense.

**Comment by pnorbert** [comment] 2020-03-16 20:04
Yes, but that would violate the current concept of attributes that they cannot be changed. Unless you throw away the new value and don't let update the attribute once it's defined.

**Comment by pnorbert** [comment] 2020-03-16 20:04
@lwan86 Can you please fix this bug then on the reader side?

**Comment by lwan86** [comment] 2020-03-16 20:07
So you are saying on the reader side, I just define the attribute the first time I see it and ignore the rest?

**Comment by pnorbert** [comment] 2020-03-16 20:09
yes. right now it throws an exception the second time, but you can just ignore it. Not a perfect solution as it will not remind the user at append time that an attribute cannot change. But it will behave identical to adios1 and non-append mode of adios2.

**Comment by lwan86** [comment] 2020-03-16 20:11
Okay. I will fix it.

**Comment by lwan86** [comment] 2020-03-23 22:49
@jychoi-hpc Could you try the latest master branch and see if this bug has been fixed?

**Comment by jychoi-hpc** [comment] 2020-03-24 17:38
@lwan86 Thank you for the fix. It works now!!

**Comment by lwan86** [comment] 2020-03-24 18:25
This bug has been fixed. Close this issue.

**Closed by lwan86** 2020-03-24 18:25 UTC
Labels: bug
