### ISSUE TITLE
SST hangs for heat2d code on Titan

### ISSUE THREAD

**Issue by swatisgupta** [ornladios/ADIOS2#710] opened 2018-07-10 18:39 UTC
I am trying to run heat2d(cpp) example using SST engine but both the codes seem to hang while trying to connect to each other (works fine with BPFile engine). The output and runtime configurations are as follows:

(1) aprun -n 12 ./heatSimulation sim.bp  4 3  5 10 10 10
Process decomposition  : 4 x 3
Array size per process : 5 x 10
Number of output steps : 10
Iterations per step    : 10
Simulation step 0: initialization
Simulation step 1
Simulation step 2
Simulation step 3
Simulation step 4
Simulation step 5
Simulation step 6
Simulation step 7
Simulation step 8
Simulation step 9
Total runtime = 37.5355s

(2) aprun -n 2 ./heatAnalysis sim.bp analysis.bp 2 1
rank 1 reads 2D slice gndx       =  20
10 x 30 from offset (10,0)
gndy       = 30
rank 0 reads 2D slice 10 x 30 from offset (0,0)

(3) Contents of adios2.xml
```
<?xml version="1.0"?>
<adios-config>
    <io name="SimulationOutput">
       <engine type="SST">
            <parameter key="DataTransport" value="wan"/>
        </engine>
    </io>
    <io name="AnalysisOutput">
        <engine type="SST">
            <parameter key="DataTransport" value="wan"/>
        </engine>
    </io>
    <io name="VizInput">
        <engine type="SST">
            <parameter key="DataTransport" value="wan"/>
        </engine>
    </io>
</adios-config>
```

(4) Changes to heat2d Makefile:
override ADIOS_INC=-I/lustre/atlas2/csc143/scratch/ssinghal/BUILDS/include
override ADIOS_LIB=-L/lustre/atlas2/csc143/scratch/ssinghal/BUILDS/lib -ladios2 -L/usr/lib64
override ADIOS_LIB+= -ladios2_sst -ladios2_evpath -ladios2_enet -ladios2_dill -ladios2_ffs -ladios2_dill -lfabric -ladios2_atl -lzmq -ldl -lbz2

(5) List of loaded modules:
  1) modules/3.2.10.6                                                             
  2) nodestat/2.2-1.0502.60539.1.31.gem                             
  3) sdb/1.1-1.0502.63652.4.27.gem                                      
  4) alps/5.2.4-2.0502.9950.37.1.gem                                   
  5) lustre-cray_gem_s/2.8.2_3.0.101_0.46.1_1.0502.8871-1.0502.0.32.1                                                                                               
  6) udreg/2.3.2-1.0502.10518.2.17.gem                                 
  7) ugni/6.0-1.0502.10863.8.28.gem                                     
  8) gni-headers/4.0-1.0502.10859.9.19.gem                         
  9) dmapp/7.0.1-1.0502.11080.8.74.gem                                
 10) xpmem/0.1-2.0502.64982.7.19.gem                               
 11) hss-llm/7.2.0                                                                      
 12) Base-opts/1.0.2-1.0502.60680.2.4.gem                          
 13) cray-mpich/7.6.3                                                              
 14) craype-network-gemini                                                    
 15) craype-interlagos
 16) craype/2.5.13
 17) lustredu/1.4
 18) xalt/0.7.5
 19) git/2.13.0
 20) module_msg/0.1
 21) modulator/1.2.0
 22) hsi/5.0.2.p1
 23) DefApps
 24) gcc/7.3.0
 25) cmake3/3.6.0
 26) cray-libsci/16.11.1
 27) pmi/5.0.9-1.0000.10911.175.4.gem
 28) atp/2.1.1
 29) PrgEnv-gnu/5.2.82

(6) ADIOS cmake configuration options used:
cmake -DCMAKE_INSTALL_PREFIX=/lustre/atlas/scratch/ssinghal/csc143/BUILDS  ../ADIOS2
-- Cray Programming Environment 2.5.13 C
-- Cray Programming Environment 2.5.13 CXX
-- Could NOT find ZFP (missing:  ZFP_LIBRARY ZFP_INCLUDE_DIR) 
-- Could NOT find SZ (missing:  SZ_LIBRARY SZ_INCLUDE_DIR) 
-- Cray Programming Environment 2.5.13 Fortran
-- Found MPI: TRUE (found version "3.1") found components:  C Fortran 
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS C) 
-- Checking for module 'libfabric>=1.6'
--   Found libfabric, version 1.6.1

-- ADIOS2 ThirdParty: Configuring KWSys

-- ADIOS2 ThirdParty: Configuring GTest

-- ADIOS2 ThirdParty: Configuring pugixml

-- ADIOS2 ThirdParty: Configuring nlohmann_json
-- Using the single-header code from /lustre/atlas/scratch/ssinghal/csc143/ADIOS2/thirdparty/nlohmann_json/nlohmann_json/single_include/

-- ADIOS2 ThirdParty: Configuring atl
-- Found atl: /lustre/atlas/scratch/ssinghal/csc143/builds/thirdparty/atl/atl/atl-config.cmake (found version "2.2.1") 

-- ADIOS2 ThirdParty: Configuring dill
-- Found dill: /lustre/atlas/scratch/ssinghal/csc143/builds/thirdparty/dill/dill/dill-config.cmake (found version "2.3.2") 

-- ADIOS2 ThirdParty: Configuring ffs
-- Found dill: /lustre/atlas/scratch/ssinghal/csc143/builds/thirdparty/dill/dill/dill-config.cmake (found suitable version "2.3.2", minimum required is "2.3.1") 
-- Found atl: /lustre/atlas/scratch/ssinghal/csc143/builds/thirdparty/atl/atl/atl-config.cmake (found suitable version "2.2.1", minimum required is "2.2.1") 
-- Found ffs: /lustre/atlas/scratch/ssinghal/csc143/builds/thirdparty/ffs/ffs/ffs-config.cmake (found version "1.5.2") 

-- ADIOS2 ThirdParty: Configuring enet
-- Found enet: /lustre/atlas/scratch/ssinghal/csc143/builds/thirdparty/enet/enet/enet-config.cmake (found version "1.3.13") 

-- ADIOS2 ThirdParty: Configuring EVPath
-- Found ffs: /lustre/atlas/scratch/ssinghal/csc143/builds/thirdparty/ffs/ffs/ffs-config.cmake (found suitable version "1.5.2", minimum required is "1.5.1") 
-- Could NOT find nvml (missing:  NVML_LIBRARY NVML_INCLUDE_DIR) 
-- Found enet: /lustre/atlas/scratch/ssinghal/csc143/builds/thirdparty/enet/enet/enet-config.cmake (found suitable version "1.3.13", minimum required is "1.3.13") 
-- Checking for module 'libfabric'
--   Found libfabric, version 1.6.1
-- Could NOT find nnti (missing:  NNTI_INCLUDE_DIR NNTI_trios_nnti_LIBRARY NNTI_trios_support_LIBRARY) 

-- Found MPI: TRUE (found version "3.1") found components:  C 

ADIOS2 build configuration:
  ADIOS Version: 2.2.0
  C++ Compiler : GNU 7.3.0 CrayPrgEnv
    /opt/cray/craype/2.5.13/bin/CC

  Fortran Compiler : GNU 7.3.0 CrayPrgEnv
    /opt/cray/craype/2.5.13/bin/ftn

  Installation prefix: /lustre/atlas/scratch/ssinghal/csc143/BUILDS
        bin: bin
        lib: lib
    include: include
      cmake: lib/cmake/adios2

  Features:
    Library Type: static (without PIC)
    Build Type:   Release
    Testing: ON
    Build Options:
      BZip2    : ON
      ZFP      : OFF
      SZ       : OFF
      MPI      : ON
      DataMan  : ON
      SST      : ON
      ZeroMQ   : ON
      HDF5     : OFF
      ADIOS1   : OFF
      Python   : OFF
      Fortran  : ON
      SysVShMem: ON

-- Configuring done
-- Generating done
-- Build files have been written to: /lustre/atlas/scratch/ssinghal/csc143/builds

**Comment by eisenhauer** [comment] 2018-07-10 18:51
The problem is with the filenames.  By the time the SST engine gets them one of those (reader or writer, don't remember which) will have an extra .bp added to it (or was it .bp removed).  Use environment variable SstVerbose=1 to see what file names the engine sees.

Hmm.  I think if you remove the .bp from the writer side command line, something in ADIOS2 will add it back and everything will work.  Extra credit if you can sort out who is adding it back and make it stop...  This is happening outside the engine, and there's really no reason for mucking with the filenames outside the engine.

**Comment by pnorbert** [comment] 2018-07-10 19:03
This is the C++ example which does not add the file extensions like the old
Fortran example.

**Comment by eisenhauer** [comment] 2018-07-10 19:13
Someone is still adding...

**Comment by swatisgupta** [comment] 2018-07-10 19:23
Thanks for suggesting SstVerbose=1. The analysis code was waiting for a reader. I changed the heatAnalysis engine configuration in adios2.xml to BPFile and it works now :). 

`Reader 0 (0xa21150): Reader 0 (0xa0ff20): Sst set to use enet as a Control Transport
Sst set to use enet as a Control Transport
Reader 0 (0xa21150): Waiting for writer response message in SstReadOpen("sim")
Reader 0 (0xa21150): finished wait writer response message in read_open
Reader 0 (0xa21150): Writer is doing FFS-based marshalling
Reader 1 (0xa0ff20): Writer is doing FFS-based marshalling
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 0, test contact", WS_stream 0xa4e3b0 for WSR Rank 0
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 1, test contact", WS_stream 0xa38570 for WSR Rank 1
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 2, test contact", WS_stream 0xa38900 for WSR Rank 2
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 3, test contact", WS_stream 0xa37da0 for WSR Rank 3
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 4, test contact", WS_stream 0xa389d0 for WSR Rank 4
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 5, test contact", WS_stream 0xa37db0 for WSR Rank 5
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 6, test contact", WS_stream 0xa37db0 for WSR Rank 6
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 7, test contact", WS_stream 0xa37db0 for WSR Rank 7
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 8, test contact", WS_stream 0xa382b0 for WSR Rank 8
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 9, test contact", WS_stream 0xa37da0 for WSR Rank 9
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 10, test contact", WS_stream 0xa38900 for WSR Rank 10
DP Reader 1 (0xa0ff20): Received contact info "Writer Rank 11, test contact", WS_stream 0xa37da0 for WSR Rank 11
DP Reader 0 (0xa21150): Reader 1 (0xa0ff20): Received contact info "Writer Rank 0, test contact", WS_stream 0xa4e3b0 for WSR Rank 0
Sending Reader Activate messages to writer
DP Reader 0 (0xa21150): Received contact info "Writer Rank 1, test contact", WS_stream 0xa38570 for WSR Rank 1
DP Reader 0 (0xa21150): Received contact info "Writer Rank 2, test contact", WS_stream 0xa38900 for WSR Rank 2
DP Reader 0 (0xa21150): Received contact info "Writer Rank 3, test contact", WS_stream 0xa37da0 for WSR Rank 3
DP Reader 0 (0xa21150): Received contact info "Writer Rank 4, test contact", WS_stream 0xa389d0 for WSR Rank 4
DP Reader 0 (0xa21150): Received contact info "Writer Rank 5, test contact", WS_stream 0xa37db0 for WSR Rank 5
DP Reader 0 (0xa21150): Received contact info "Writer Rank 6, test contact", WS_stream 0xa37db0 for WSR Rank 6
DP Reader 0 (0xa21150): Received contact info "Writer Rank 7, test contact", WS_stream 0xa37db0 for WSR Rank 7
DP Reader 0 (0xa21150): Received contact info "Writer Rank 8, test contact", WS_stream 0xa382b0 for WSR Rank 8
DP Reader 0 (0xa21150): Received contact info "Writer Rank 9, test contact", WS_stream 0xa37da0 for WSR Rank 9
DP Reader 0 (0xa21150): Received contact info "Writer Rank 10, test contact", WS_stream 0xa38900 for WSR Rank 10
DP Reader 0 (0xa21150): Received contact info "Writer Rank 11, test contact", WS_stream 0xa37da0 for WSR Rank 11
Reader 0 (0xa21150): Sending Reader Activate messages to writer
Reader 0 (0xa21150): Finish opening Stream "sim", starting with Step number 0
Reader 0 (0xa21150): Wait for next metadata after last timestep -1
Reader 0 (0xa21150): Waiting for metadata for a Timestep later than TS -1
Reader 0 (0xa21150): Stream status is 1
Reader 1 (0xa0ff20): Finish opening Stream "sim", starting with Step number 0
Reader 1 (0xa0ff20): Wait for next metadata after last timestep -1
Reader 1 (0xa0ff20): Waiting for metadata for a Timestep later than TS -1
Reader 1 (0xa0ff20): Stream status is 1
Reader 0 (0xa21150): Reader 1 (0xa0ff20): Received an incoming metadata message for timestep 0
Received an incoming metadata message for timestep 0
Reader 0 (0xa21150): Reader 1 (0xa0ff20): Received an incoming metadata message for timestep 1
Received an incoming metadata message for timestep 1
Reader 1 (0xa0ff20): Reader 0 (0xa21150): Returning metadata for Timestep 0
Returning metadata for Timestep 0
Reader 0 (0xa21150): Reader 1 (0xa0ff20): SstAdvanceStep returning Success on timestep 0
SstAdvanceStep returning Success on timestep 0
gndx       = 20
gndy       = 30
rank 1 reads 2D slice 10 x 30 from offset (10,0)
rank 0 reads 2D slice 10 x 30 from offset (0,0)
Writer 0 (0xa32480): Writer 0 (0xa47fa0): Sst set to use enet as a Control Transport
Writer 0 (0xa47fa0): Loading DataPlane "evpath"
Reader 1 (0xa0ff20): Received an incoming metadata message for timestep 2
Sst set to use enet as a Control Transport
Writer 0 (0xa32480): Loading DataPlane "evpath"
Writer 1 (0xa32480): Opening Stream "analysis.bp"
Writer 1 (0xa32480): Stream "analysis.bp" waiting for 1 readers
Reader 0 (0xa21150): Received an incoming metadata message for timestep 2
Reader 0 (0xa21150): Received an incoming metadata message for timestep 3
Reader 1 (0xa0ff20): Received an incoming metadata message for timestep 3
Reader 1 (0xa0ff20): Reader 0 (0xa21150): Received an incoming metadata message for timestep 4
Received an incoming metadata message for timestep 4
Reader 1 (0xa0ff20): Received an incoming metadata message for timestep 5
Reader 0 (0xa21150): Received an incoming metadata message for timestep 5
Reader 0 (0xa21150): Received an incoming metadata message for timestep 6
Reader 1 (0xa0ff20): Received an incoming metadata message for timestep 6
Reader 1 (0xa0ff20): Reader 0 (0xa21150): Received an incoming metadata message for timestep 7
Received an incoming metadata message for timestep 7
Reader 1 (0xa0ff20): Reader 0 (0xa21150): Received an incoming metadata message for timestep 8
Received an incoming metadata message for timestep 8
Reader 0 (0xa21150): Received an incoming metadata message for timestep 9
Reader 1 (0xa0ff20): Received an incoming metadata message for timestep 9
Reader 0 (0xa21150): Received a writer close message. Timestep 9 was the final timestep.
Reader 1 (0xa0ff20): Received a writer close message. Timestep 9 was the final timestep.
**Writer 0 (0xa47fa0): Opening Stream "analysis.bp"**
**Writer 0 (0xa47fa0): Stream "analysis.bp" waiting for 1 readers**`

**Comment by eisenhauer** [comment] 2019-05-23 20:43
This was identified as working in Swatis' last comment, so closing...

**Closed by eisenhauer** 2019-05-23 20:43 UTC
