### ISSUE TITLE
make install fails due to auto detection of CUDA during CMake 'adios2-config dummy'

### ISSUE THREAD

**Issue by cwsmith** [ornladios/ADIOS2#2993] opened 2022-01-05 16:19 UTC
**Describe the bug**

ADIOS2 master@c8432b3 builds with GCC 10 and CUDA disabled without any obvious errors using the following CMake command:

`cmake ../ADIOS2/ -DCMAKE_INSTALL_PREFIX=$PWD/install -DADIOS2_USE_CUDA=OFF`

The subsequent call to `make install` fails during `Configuring adios2-config dummy CMake project` when CUDA 10.2 is automatically detected and enabled instead of respecting the flag I passed to disable CUDA from my above CMake command.

The error is below:

```
-- Installing: /space/cwsmith/wdmCpl/buildAdios2/install/lib64/cmake/adios2/adios2-targets-release.cmake
-- Installing: /space/cwsmith/wdmCpl/buildAdios2/install/lib64/cmake/adios2/adios2-config.cmake
/tmp/tmp.31EwZWZJMH /space/cwsmith/wdmCpl/buildAdios2
Configuring adios2-config dummy CMake project
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpicxx
-- Check for working CXX compiler: /opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpicxx - broken
CMake Error at /opt/scorec/cmake/3.20.0/share/cmake-3.20/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "/opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpicxx"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /tmp/tmp.31EwZWZJMH/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_09c4d/fast && gmake[1]: Entering directory `/tmp/tmp.31EwZWZJMH/CMakeFiles/CMakeTmp'
    /usr/bin/gmake  -f CMakeFiles/cmTC_09c4d.dir/build.make CMakeFiles/cmTC_09c4d.dir/build
    gmake[2]: Entering directory `/tmp/tmp.31EwZWZJMH/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_09c4d.dir/testCXXCompiler.cxx.o
    /opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpicxx    -o CMakeFiles/cmTC_09c4d.dir/testCXXCompiler.cxx.o -c /tmp/tmp.31EwZWZJMH/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    In file included from /usr/local/cuda-10.2/bin/../targets/x86_64-linux/include/cuda_runtime.h:83,
                     from <command-line>:
    /usr/local/cuda-10.2/bin/../targets/x86_64-linux/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
          |  ^~~~~
    gmake[2]: *** [CMakeFiles/cmTC_09c4d.dir/testCXXCompiler.cxx.o] Error 1
    gmake[2]: Leaving directory `/tmp/tmp.31EwZWZJMH/CMakeFiles/CMakeTmp'
    gmake[1]: *** [cmTC_09c4d/fast] Error 2
    gmake[1]: Leaving directory `/tmp/tmp.31EwZWZJMH/CMakeFiles/CMakeTmp'
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.31EwZWZJMH/CMakeFiles/CMakeOutput.log".
See also "/tmp/tmp.31EwZWZJMH/CMakeFiles/CMakeError.log".
Failed
CMake Error at cmake/install/post/cmake_install.cmake:49 (message):
  generate-adios2-config.sh returned 1, should be 0
Call Stack (most recent call first):
  cmake_install.cmake:58 (include)


make: *** [install] Error 1

```

**To Reproduce**

```
git clone git@github.com:ornladios/ADIOS2.git
mkdir buildAdios2
cd !$
# using gcc 10.1.0
cmake ../ADIOS2/ -DCMAKE_INSTALL_PREFIX=$PWD/install -DADIOS2_USE_CUDA=OFF
make -j8 # succeeds
make install # fails
```

**Expected behavior**

The install completes without error.

**Desktop (please complete the following information):**
 - OS/Platform: RHEL7
 - Build: gcc 10.1.0, cmake 3.20

**Additional context**

None.

**Following up**

Was the issue fixed? Please report back.

**Comment by cwsmith** [comment] 2022-01-05 19:55
Passing `-DADIOS2_INSTALL_GENERATE_CONFIG=OFF` to CMake avoids the install error.

**Comment by vicentebolea** [comment] 2022-01-25 21:06
I am having difficulties reproducing this error. I have proposed a possible solution for it at #3016, however, I am unsure that it really fix this issues as I cannot reproduce it.

Could you checkout my branch to see if you still observer the same issue?

**Comment by cwsmith** [comment] 2022-01-26 15:29
Hi @vicentebolea.  

Unfortunately (or fortunately), this 'bug' appears to be result of my mistake...  The shell I was building in had the `MPICH_CXX` environment variable set to the Kokkos `nvcc_wrapper` script (from a prior build) instead of `g++`.  Setting `MPICH_CXX=/path/to/g++` results in `make install` for master@c8432b3, and `vicentebolea:fix-2993-dummy-project-error-cuda` to complete without errors.

I'm sorry for the hassle.  Thank you for the help and the proposed fix.

I'm not sure if it matters now, but there is a warning in the post-install cmake configure in `vicentebolea:fix-2993-dummy-project-error-cuda`.  A portion of the cmake output is pasted below.

```
-- Installing: /space/cwsmith/wdmCpl/buildAdios2_fix2993/install/lib64/cmake/adios2/adios2-targets-release.cmake
-- Installing: /space/cwsmith/wdmCpl/buildAdios2_fix2993/install/lib64/cmake/adios2/adios2-config.cmake
/tmp/tmp.Y2bDh7quG0 /space/cwsmith/wdmCpl/buildAdios2_fix2993
Configuring adios2-config dummy CMake project
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpicc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpicxx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_C: /opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpicc (found version "3.1") 
-- Found MPI_CXX: /opt/scorec/spack/v0154_2/install/linux-rhel7-x86_64/gcc-10.1.0/mpich-3.3.2-gi3wrjquyo564rk27x6r2c6ilr7ndmpl/bin/mpicxx (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found adios2: /space/cwsmith/wdmCpl/buildAdios2_fix2993/install/lib64/cmake/adios2/adios2-config.cmake (found version "2.7.1.1059") found components: C CXX MPI 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ADIOS2_USE_CUDA


-- Build files have been written to: /tmp/tmp.Y2bDh7quG0
<snip...>
```

**Comment by vicentebolea** [comment] 2022-01-26 17:52
@cwsmith No problem, this definitely closes the mystery. In any case is good that you reported this and later explained why it happens, hopefully google will index this for the next person having the same issue :)

**Comment by vicentebolea** [comment] 2022-01-26 17:52
Closing this

**Closed by vicentebolea** 2022-01-26 17:52 UTC
