### ISSUE TITLE
Cannot quit SST reader using Python binding if writer is absent

### ISSUE THREAD

**Issue by keichi** [ornladios/ADIOS2#1491] opened 2019-06-12 03:35 UTC
SST reader ignores SIGINT and refuses to quit if the writer is absent. I need to use kill(1) to terminate the reader.

```
^CSerious internal error.  Use of condition 4974, no longer in control list
^CSerious internal error.  Use of condition 10921, no longer in control list
^CSerious internal error.  Use of condition 11178, no longer in control list
^CSerious internal error.  Use of condition 11489, no longer in control list
^CSerious internal error.  Use of condition 11825, no longer in control list
...
```

Minimal reproducible example:

```python
import adios2

adios = adios2.ADIOS()
io = adios.DeclareIO("test")

io.SetEngine("SST")

reader = io.Open("foo.bp", adios2.Mode.Read)
```

This does not happen when using the C++ binding.

**Comment by eisenhauer** [comment] 2019-06-14 15:10
Sorry Keichi, this is a python thing and not something I can address in SST.  Python catches the signal and queues it for delivery when control returns back to python from the C/C++ level.  What is really necessary to "fix" this is for Python not to catch it and to allow it to truly interrupt the low-level wait that is happening in SST.  I'll leave this open in the event that someone else has an idea on this, but I think Python considers this a feature.  Just installing a Python-level handler for SIGINT for example doesn't work here because it won't be called until C++ returns, which it won't because it's waiting...

**Comment by eisenhauer** [comment] 2019-06-14 15:41
I should be more specific:  Open() in ADIOS2 is something that succeeds or fails.  By convention in the streaming engines in ADIOS readers wait for streams to be created if they aren't present quite at the time of Open() (this saves problems with race conditions on open, etc.) . In the current semantic, Open() doesn't time out, so it'll keep waiting regardless.  Fixing this issue with Python would require one of two approaches:  1) change Open() so that it has a timeout.  (This isn't unreasonable, but it also doesn't directly tackle the underlying issue, that Python can't/doesn't interrupt running C/C++ calls.), or 2) rework the ADIOS2 C++ API so that there is a TryOpen() call that might be used in the Python API particularly.  Apparently the standard approach to this situation is to limit the duration of C/C++ interface calls, returning to Python regularly.  TryOpen() would allow the re-implementation of portions of ADIOS2 streaming (the waiting for the writer to start bits) in Python such that it would more nicely mesh with Python signal handling mechanics.  (There might be calls other than open() that would require this treatment too if we wanted great Python operation, but Open() seems to be the big one.) 
 @pnorbert can maybe opine on the desirability of these approaches.  Both would/could apply to all streaming engines (except InSitu, which is kind of special).

**Comment by pnorbert** [comment] 2019-06-14 16:42
That would work. I guess in both cases (Open with timeout, and TryOpen),
the python implementation of Open should call them in a loop and implement
the timeout itself. Similarly, BeginStep should be implemented in Python
then, always calling the C++ BeginStep with a small or zero timeout.

**Comment by germasch** [comment] 2019-06-14 19:15
In terms of a `TryOpen`, one option to consider would be using the existing `Open` with a flag (kinda like `O_NONBLOCK` with POSIX open). Interpreting the `Mode` flag as a bitmask might also be handy in other situations, like where you may want to indicate that you want to open in streaming mode, which was brought up here before.

Besides that, I'm not actually sure that I think a blocking `Open` waiting for a file or a stream to appear is all that intuitive. (In particular, because right now, it won't wait for a file to appear, it'll error in that case). It wouldn't seem unreasonable to me to have `Open` fail if a stream doesn't yet exist, but I gather there's some kind of race condition argument?

**Comment by eisenhauer** [comment] 2019-06-18 15:19
I'd argue that while immediate-fail-or-succeed makes sense for files (where each stage of a pipeline must not only start, but generally finish, before the next one begins), it makes a whole lot less sense for streams where things will by design run concurrently.   Open is more of a 'rendezvous', and in that sense *someone* will get to the rendezvous first.  Guaranteeing that it is always the writer is difficult, unless you add an external mechanism (which doesn't simplify things, just moves the complexity somewhere else).   We have a currently unused something in the API, SetStreamOpenMode(), which is commented as "not yet implemented", where the options are Wait and NoWait.  We could use that, but I'd probably recommend having a ReaderOpenTimeout value as an engine parameter.  Set the default to something like 60 seconds (as a guess) to get us past CI races and be a reasonable amount of time for someone to start a writer in a debugger, etc.  Python could set a shorter timeout and call it in a loop.

The other question is how to make it work with Open(), which returns a reference to an Engine object.  We can't simply return NULL, so presumably we need to raise a timeout exception, have python catch that, etc.  Presumably one can catch a C++ exception in Python...  I haven't gone there, so I don't know how much trouble that is.  While the SST end of this stuff is easy, I'd just as soon kick the python stuff to someone who actually has a clue about it.

@pnorbert StreamOpenMode is not the only bit of flotsam in ADIOSTypes.h.  ReadMode is also unused (could be I suppose, but isn't).  IOMode is I guess in there for speculative purposes?  We might want to clean up this stuff...

**Comment by eisenhauer** [comment] 2019-06-19 16:08
Hi Keichi,
I have a PR that at least addresses the SST portion of this.  I'll open another issue regarding the re-implementation of Python bindings that might address this more fully.  However, before I close this issue, I'm curious about the "^CSerious internal error.  Use of condition 4974, no longer in control list" artifacts that you include above.   I was *not* able to reproduce that, at least with my install of ADIOS2, version of Python and test program (the minimal example you provide).  However, I think it's interesting, because that printf() is coming from the lowest levels of EVPath, which implies that at least under some circumstances, the ^C is not just intercepted by Python, but has some impact which we *might* have used to handle it at a lower level too.  In all honesty, I'm not sure it can really change anything substantial.  Python's "feature" of overriding ^C handling itself so that it can be managed with Python handlers, rather than library-based handlers, is pretty established and well-documented, and it's what I saw when experimenting on my own.  But I'm curious why you saw something slightly different and if it might be Python version differences, OS differences, or an artifact of something else you might have done to try to deal with the problem.  Any idea?

**Comment by keichi** [comment] 2019-06-20 10:36
@eisenhauer Here is my dev environment:

- macOS Mojave 10.14.5 (18F132)
- Python 3.7.3
- ADIOS2 98f2c773, no modifications made

I was not able to reproduce the  "^CSerious internal error. Use of condition 4974, no longer in control list" message on my Linux workstation with the same Python and ADIOS2 versions. So I guess it's specific to macOS?

**Comment by eisenhauer** [comment] 2019-06-24 11:19
Thanks Keichi.  Actually, I'm impressed you got the python stuff working with OSX.  I do half my work on macOS, but getting python3 working there for ADIOS2 without blowing up the system python2 installation was more trouble than I wanted to go to, so I was playing with this in a Linux VM.  I think this behaviour might indeed be specific to OSX, so I'm not going to pursue it.  I'll just close this issue and create a more generic Python bindings one.

**Closed by eisenhauer** 2019-06-24 11:19 UTC
Labels: bug
