### ISSUE TITLE
Race condition in SST engine, resulting in rare segfaults 

### ISSUE THREAD

**Issue by franzpoeschel** [ornladios/ADIOS2#2319] opened 2020-06-10 14:07 UTC
**Describe the bug**
When testing streaming via ADIOS2's SST engine in the openPMD API, I noticed that [one of my tests](https://github.com/franzpoeschel/openPMD-api/blob/59e9e397ae89b3019fdc8344bd2a9918612f378c/test/SerialIOTest.cpp#L2567) would seldomly crash with a segfault. This test opens an SST reader and an SST writer concurrently as two threads in the same process.

**To Reproduce**
I tried to build a similar example using only ADIOS2 and was able to reproduce the random segfaulting with a small example:

```cpp
#include <adios2.h>
#include <array>
#include <future>
#include <iostream>
#include <numeric>
#include <thread>
#include <condition_variable>
#include <shared_mutex>

using dt = long long;

struct synchronize
{
    std::condition_variable_any cond;
    std::shared_mutex mutex;
    bool start = false;
};

void
read( synchronize & s )
{
    adios2::ADIOS adios;
    adios2::IO bpIO = adios.DeclareIO( "IO" );
    bpIO.SetEngine( "sst" );

    // {
    //     std::shared_lock lk( s.mutex );
    //     s.cond.wait( lk, [ &s ]() { return s.start; } );
    // }
    adios2::Engine bpReader = bpIO.Open( "communicate", adios2::Mode::Read );

    std::array< dt, 100000 > ar;

    auto status = bpReader.BeginStep();
    if( status == adios2::StepStatus::EndOfStream )
    {
        return;
    }

    adios2::Variable< dt > var = bpIO.InquireVariable< dt >( "data" );
    bpReader.Get( var, ar.begin() );
    bpReader.EndStep();
    for( auto val : ar )
    {
        // std::cout << val << ", ";
    }
    bpReader.Close();
}


void
write( synchronize & s )
{
    adios2::ADIOS adios;
    adios2::IO bpIO = adios.DeclareIO( "IO" );
    bpIO.SetEngine( "sst" );
    // {
    //     std::shared_lock lk( s.mutex );
    //     s.cond.wait( lk, [ &s ]() { return s.start; } );
    // }
    adios2::Engine bpWriter = bpIO.Open( "communicate", adios2::Mode::Write );

    auto var = bpIO.DefineVariable< dt >(
        "data",
        adios2::Dims{ 10000, 10 },
        adios2::Dims{ 0, 0 },
        adios2::Dims{ 10000, 10 } );

    std::array< dt, 100000 > ar;

    std::iota( ar.begin(), ar.end(), 0 );

    bpWriter.BeginStep();
    bpWriter.Put< dt >( var, ar.begin() );
    bpWriter.EndStep();
    bpWriter.Close();
}

int
main()
{
    synchronize s;
    auto read_fut = std::async( std::launch::async, read, std::ref( s ) );
    auto write_fut = std::async( std::launch::async, write, std::ref( s ) );
    // std::this_thread::sleep_for( std::chrono::milliseconds( 200 ) );
    // {
    //     std::lock_guard lk( s.mutex );
    //     s.start = true;
    // }
    s.cond.notify_all();
    read_fut.wait();
    write_fut.wait();
}
```
(I tried including some locking mechanisms to trigger the issue more reliably, but when commenting those pieces in, I wasn't able to reproduce the issue at all. Left it in for now since it may or may not be helpful in chasing down the issue. Requires C++17 to build.)
CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.1)
project(adios2_test)
find_package(ADIOS2 REQUIRED)
add_executable(concurrent concurrent.cpp)
set_target_properties(concurrent PROPERTIES CXX_STANDARD 17)
target_link_libraries(concurrent adios2::adios2)
```

Concurrency being concurrency, this issue is not always triggered. Sample output:
```bash
> i=0; while true; do echo "$((i++))"; ./concurrent || break; done
0
1
2
3
4
[…]
29
30
31
Segmentation fault (core dumped)
```

**Expected behavior**
Should not crash. I am not sure whether this can also be triggered when communicating between different processes. If not, this might be also wrong usage of the SST engine.

**Desktop (please complete the following information):**
 - Platform: Ubuntu 20.04, Intel Core i5-6200U, 
 - Build g++ 9.3.0, dynamic build, latest master (130c4f14)

**Comment by franzpoeschel** [comment] 2020-06-10 22:52
Maybe a little note in the SST documentation that it is intended for communication between different processes could be useful? But that's up to you, from my side, this issue can be closed.
Thanks for the quick help again!

**Comment by eisenhauer** [comment] 2020-06-11 17:02
I'm preparing a PR that protects SST's shared state in this circumstance (it isn't extensive) and have a modified version of your test that can work as a regression test for our engines.  Once I get it done, I'll see if there are other engines with problems.  But yes, in general the ADIOS staging engines are not intended for intra-process communication.   The exception to that is the inline engine, which is a different sort of beast...

**Comment by franzpoeschel** [comment] 2020-06-11 22:53
Sounds great!

**Comment by eisenhauer** [comment] 2020-06-16 22:29
PR #2334, just merged with master, supports this thread-to-thread use case.  (Beyond testing, whether or not it makes sense to use a socket or RDMA-based transport for thread-to-thread communication is another matter!)

**Closed by eisenhauer** 2020-06-16 22:29 UTC
