### ISSUE TITLE
f951: Fatal Error: Reading module ‘mpivars’ at line 1525 column 47: Unexpected EOF

### ISSUE THREAD

**Issue by brioglade** [ornladios/ADIOS2#4241] opened 2024-07-11 23:59 UTC
hi, what's the problem?

[  8%] Building C object thirdparty/dill/dill/CMakeFiles/dill.dir/x86_64_disassembler.c.o
f951: Fatal Error: Reading module ‘mpivars’ at line 1525 column 47: Unexpected EOF
compilation terminated.
make[2]: *** [examples/basics/globalArray1D/CMakeFiles/adios2_basics_globalArray1D_decomp_f.dir/build.make:75: examples/basics/globalArray1D/CMakeFiles/adios2_basics_globalArray1D_decomp_f.dir/decomp.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2717: examples/basics/globalArray1D/CMakeFiles/adios2_basics_globalArray1D_decomp_f.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  9%] Building CXX object source/adios2/CMakeFiles/adios2_hdf5.dir/engine/hdf5/HDF5WriterP.cpp.o

**Comment by eisenhauer** [comment] 2024-07-12 00:07
Not enough here to go on, but maybe try again with a serial make?  (I.E. no -j value.)

**Comment by brioglade** [comment] 2024-07-12 03:31
There is another errr with no -j value.

[ 58%] Building Fortran object bindings/Fortran/CMakeFiles/adios2_fortran.dir/modules/adios2_adios_init_serial_smod.F90.o
f951: Fatal Error: Reading module ‘adios2_functions_mod’ at line 1507 column 61: Unexpected EOF
compilation terminated.
make[2]: *** [bindings/Fortran/CMakeFiles/adios2_fortran.dir/build.make:237: bindings/Fortran/CMakeFiles/adios2_fortran.dir/modules/adios2_adios_init_serial_smod.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2417: bindings/Fortran/CMakeFiles/adios2_fortran.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by eisenhauer** [comment] 2024-07-12 03:47
You might try a make clean first in case something got corrupted.  This doesn't look like a source-level error.  Rather fortran is somehow not happy with a module file created by an earlier fortran run.  You don't say what system you're trying to build on, but other mentions of this sort of error I find online seem to be caused by compiler issues.  You might be able to get sysadmin help if you're on a managed system.

**Comment by brioglade** [comment] 2024-07-12 04:22
Ubuntu22.04 gfortran9.5.0
I delete adois2-build and re-compile but error still. I had compiled it in other system and it worked well. I have tried many times and don't know why.

**Comment by eisenhauer** [comment] 2024-07-12 10:06
Googling for "f951: Fatal Error: Reading module" and EOF reveals other hits you might explore, but I think this is not an ADIOS problem.

**Comment by HakunanMatatat** [comment] 2024-07-13 08:00
It‘s OK. "sudo make -j 16" should use sudo.

**Comment by eisenhauer** [comment] 2024-07-13 10:58
Unless there's further info, I'm going to close this as an environment problem not related to ADIOS.  You can reopen if necessary.

**Closed by eisenhauer** 2024-07-13 10:58 UTC
