### ISSUE TITLE
Linking error when building from source with GCC10

### ISSUE THREAD

**Issue by massimiliano-leoni** [ornladios/ADIOS2#3050] opened 2022-02-09 10:47 UTC
**Describe the bug**
Building from source fails at link time when compiling with GCC10 with several "undefined reference" errors.
An example:

```
[ 33%] Linking CXX executable ../../../bin/adios2_iotest
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<std::complex<float> >::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<unsigned short>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<char>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<long>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<signed char>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<unsigned char>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<unsigned long>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<unsigned int>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<unsigned long long>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<std::complex<double> >::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<short>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<double>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<float>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<long double>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<int>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
/usr/bin/ld: ../../../lib/libadios2_cxx11.so.2.7.1: undefined reference to `adios2::Variable<long long>::ToBlocksInfoMin(adios2::MinVarInfo const*) const'
collect2: error: ld returned 1 exit status
```

**To Reproduce**

0. Install the GCC10 compiler collection via `sudo apt install gcc-10 g++-10`
1. `git clone https://github.com/ornladios/ADIOS2.git`
2. `mkdir ADIOS2/build`
3. `cd ADIOS2/build`
4. `cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -DCMAKE_C_COMPILER=/usr/bin/gcc-10 ..`
5. `make`

**Expected behavior**
The compilation works.

**Desktop (please complete the following information):**
 - OS/Platform: KDE Neon [based on Ubuntu 20.04 Focal Fossa].
 - Build: everything default minus the compiler specification.

**Additional context**
The build works fine with GCC9, which is the default on Ubuntu 20.04, but I've experienced the same bug on multiple clusters with GCC10.

**Following up**
Was the issue fixed? Please report back.

**Comment by eisenhauer** [comment] 2022-02-09 14:24
Thanks for the problem report.  We don't yet have gcc10 in CI, but PR  #3051 fixes this in testing.   However, I'll let you test after that's merged rather than closing this automatically...

**Comment by massimiliano-leoni** [comment] 2022-02-09 14:29
Perfect, I'll stand-by and confirm the fix after the merge then.

**Comment by massimiliano-leoni** [comment] 2022-02-09 14:51
I confirm that revision https://github.com/ornladios/ADIOS2/commit/582cd512e49786393b4ab3b5800317d6e0863e04 compiles fine with GCC10.

**Comment by dmitry-ganyushin** [comment] 2022-02-09 14:57
That is nice, but for real projects I would suggest using the release version or some tagged version, unless you have a specific reason not to do it like a missing feature. Those are the most fully tested versions and it is also good for reproducibility of the results.

**Comment by massimiliano-leoni** [comment] 2022-02-09 16:23
Yes, I understand that. I'll switch back to master as soon as the pull request above is merged.

**Comment by eisenhauer** [comment] 2022-02-09 16:39
Unfortunately, what we do have in CI currently is a required test environment that often doesn't complete its testing within the 2-hour time limit (at least when azure pipelines seems to be more loaded).  That's what caused the PR to fail it's first round.  I've kicked it to rerun, but if that environment times out again I'll suspend that test environment and go ahead with the merge...

**Closed** 2022-02-10 09:47 UTC
